add(rbac): add oidc-viewer, vault login using k8s jwt

diff --git a/.github/workflows/tfaa.yml b/.github/workflows/tfaa.yml
--- a/.github/workflows/tfaa.yml
+++ b/.github/workflows/tfaa.yml
@@ -11,6 +11,11 @@ on:
         type: boolean
         required: false
         default: false
+      login-vault-in-cluster-sa:
+        description: "Login to Vault using in cluster k8s service account"
+        required: false
+        default: false
+        type: boolean
       install-sops:
         type: boolean
         required: false
@@ -46,6 +51,14 @@ on:
         type: string
         required: false
         default: ap-southeast-1
+      SA_TOKEN_PATH:
+        type: string
+        required: false
+        default: /var/run/secrets/kubernetes.io/serviceaccount/token
+      VAULT_ADDR:
+        type: string
+        required: false
+        default: https://vault.tuana9a.com
     secrets:
       VAULT_TOKEN:
         required: false
@@ -60,6 +73,8 @@ env:
   DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
   TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
   TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
+  VAULT_ADDR: ${{ inputs.VAULT_ADDR }}
+  SA_TOKEN_PATH: ${{ inputs.SA_TOKEN_PATH }}
 
 jobs:
   tfaa:
@@ -111,6 +126,25 @@ jobs:
         run: |
           curl -sSf -X GET https://vault.tuana9a.com/v1/kv/github.com/tuana9a/platform/${{ inputs.WORKING_DIR }}/terraform -H "X-Vault-Token: ${{ secrets.VAULT_TOKEN }}" -o vault_data.json
           for x in $(jq -r '.data._files_' vault_data.json); do echo "=== $x ==="; jq -r '.data."'$x'"' vault_data.json > $x; done
+      - name: Login to Vault using k8s SA JWT
+        if: "${{ inputs.login-vault-in-cluster-sa }}"
+        run: |
+          JWT=$(cat "${SA_TOKEN_PATH}")
+
+          VAULT_TOKEN=$(curl -sS \
+            --fail \
+            --request POST \
+            --header "X-Vault-Request: true" \
+            --data "{\"jwt\":\"${JWT}\",\"role\":\"gha-sa\"}" \
+            "${VAULT_ADDR}/v1/auth/in-cluster/login" | jq -r '.auth.client_token')
+
+          if [ -z "$VAULT_TOKEN" ] || [ "$VAULT_TOKEN" = "null" ]; then
+            echo "Failed to obtain Vault token" >&2
+            exit 1
+          fi
+
+          echo "::add-mask::$VAULT_TOKEN"
+          echo "VAULT_TOKEN=$VAULT_TOKEN" >> "$GITHUB_ENV"
       - id: tfinit
         name: tfinit
         working-directory: "${{ inputs.WORKING_DIR }}"
